GET https://better-friend-server.herokuapp.com/dates/1 HTTP/1.1
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG41NTUiLCJwYXNzd29yZCI6IiQyYSQxMiRuMnVlVDVoTFlDdVpqei5BdzdqQU51SDhITWlSZmNHUXYzODFsYUx1NTZxaEJleURRdkEzaSIsImlhdCI6MTU1NTUyNTMwOCwiZXhwIjoxNTU1NjExNzA4fQ.pSE5Ih6qwXm5KAN7XqLPqUiY5rgUPbH9uB0Hn3j-5dw

